name: Compress and Upload FreeBSD Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download FreeBSD binary
      run: |
        wget https://download.freebsd.org/ftp/releases/VM-IMAGES/13.3-RELEASE/amd64/Latest/FreeBSD-13.3-RELEASE-amd64.raw.xz -O FreeBSD.raw.xz

    - name: Set up FreeBSD environment with QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 qemu-utils
        unxz FreeBSD.raw.xz
        qemu-img resize -f raw FreeBSD.raw +5G
        sudo modprobe nbd max_part=8
        sudo qemu-nbd --format=raw --connect=/dev/nbd0 FreeBSD.raw
        sudo mount /dev/nbd0p2 /mnt
        sudo mkdir -p /mnt/workspace
        sudo cp server /mnt/workspace/

    - name: Compress binary with UPX in FreeBSD
      run: |
        sudo chroot /mnt /bin/sh -c "pkg install -y upx && cd /workspace && upx --best --lzma -o server_compressed server"

    - name: Copy compressed binary back to host
      run: |
        sudo cp /mnt/workspace/server_compressed .

    - name: Set up GitHub CLI with PAT
      run: |
        sudo apt-get update
        sudo apt-get install -y gh
        echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

    - name: Upload compressed binary to GitHub Releases
      run: |
        gh release create freebsd -t "FreeBSD Release" -n "Compressed FreeBSD binary" || true
        gh release upload freebsd server_compressed --clobber
