name: Compress and Upload Binary with UPX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compress-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Download binary file
      run: |
        wget https://github.com/eooce/test/releases/download/freebsd/server -O server

    - name: Install UPX
      run: |
        sudo apt-get update
        sudo apt-get install -y upx

    - name: Compress binary with UPX
      run: |
        upx --best --lzma -o server_compressed server

    - name: Set up GitHub CLI with PAT
      run: |
        sudo apt-get update
        sudo apt-get install -y gh
        echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

    - name: Upload compressed binary to GitHub Releases
      run: |
        gh release create freebsd -t "FreeBSD Release" -n "Compressed FreeBSD binary" || true
        gh release upload freebsd server_compressed --clobber
